
import java.sql.Blob;
import java.sql.ResultSet;
import database.StudentsRepository;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import utils.Utility;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author vhalv
 */
public class Tlobby extends javax.swing.JFrame {

    private Utility utils = new Utility();
    private StudentsRepository repo = new StudentsRepository();
    private int mouseX, mouseY;
    private Map<Integer, JTable> mapTable = new HashMap<>();

    public Tlobby() {
        initComponents();
        sRecords.setVisible(false);
        sRecords.repaint();
        sRecords.revalidate();
        this.setGlassPane(sRecords);
        mapTable.put(0, tbIctHope);
        mapTable.put(1, tbIctLove);
        mapTable.put(2, tbHumssLove);
        mapTable.put(3, tbHumssHope);
        mapTable.put(4, tbHumssFaith);
        mapTable.put(5, tbAbmLove);
        mapTable.put(6, tbStemHope);

        this.addListenersForAllTableInTabbed();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopMenu = new javax.swing.JPopupMenu();
        jDeleteStudent = new javax.swing.JMenuItem();
        jStudentInfo = new javax.swing.JMenuItem();
        sRecords = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblProfilePicture = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblTimeInOut = new javax.swing.JTable();
        lbNameStd = new javax.swing.JLabel();
        lbStudentId = new javax.swing.JLabel();
        lbYearlLevel = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        lbContactStd = new javax.swing.JLabel();
        lbAddressStd = new javax.swing.JLabel();
        lbStationStd = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addstudent = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        barcode = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        P1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        studentInfoTab = new javax.swing.JTabbedPane();
        pIctHope = new javax.swing.JPanel();
        test1 = new javax.swing.JScrollPane();
        tbIctHope = new javax.swing.JTable();
        pIctLove = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbIctLove = new javax.swing.JTable();
        pHumsHope = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbHumssHope = new javax.swing.JTable();
        pHumssLove = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbHumssLove = new javax.swing.JTable();
        pHumssFaith = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbHumssFaith = new javax.swing.JTable();
        pAbmLove = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbAbmLove = new javax.swing.JTable();
        pStemHope = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbStemHope = new javax.swing.JTable();

        jDeleteStudent.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jDeleteStudent.setText("DELETE");
        jDeleteStudent.setToolTipText("");
        jDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteStudentActionPerformed(evt);
            }
        });
        jPopMenu.add(jDeleteStudent);
        jDeleteStudent.getAccessibleContext().setAccessibleName("Menu2");

        jStudentInfo.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jStudentInfo.setText("ACCOUNT");
        jStudentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStudentInfoActionPerformed(evt);
            }
        });
        jPopMenu.add(jStudentInfo);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sRecords.setBackground(new java.awt.Color(232, 233, 215));

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel6.setText("STUDENT RECORDS");

        jPanel14.setBackground(new java.awt.Color(117, 117, 117));
        jPanel14.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        lblProfilePicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tblTimeInOut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATE", "TIME IN", "TIME OUT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTimeInOut.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(tblTimeInOut);
        if (tblTimeInOut.getColumnModel().getColumnCount() > 0) {
            tblTimeInOut.getColumnModel().getColumn(0).setResizable(false);
            tblTimeInOut.getColumnModel().getColumn(1).setResizable(false);
            tblTimeInOut.getColumnModel().getColumn(2).setResizable(false);
        }

        lbNameStd.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbNameStd.setText("Name:");

        lbStudentId.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbStudentId.setText("Student ID:");

        lbYearlLevel.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbYearlLevel.setText("Grade / Section:");

        btnExit.setBackground(new java.awt.Color(0, 102, 51));
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lbContactStd.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbContactStd.setText("Contact no.");

        lbAddressStd.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbAddressStd.setText("Address");

        lbStationStd.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lbStationStd.setText("Station");

        javax.swing.GroupLayout sRecordsLayout = new javax.swing.GroupLayout(sRecords);
        sRecords.setLayout(sRecordsLayout);
        sRecordsLayout.setHorizontalGroup(
            sRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sRecordsLayout.createSequentialGroup()
                .addGroup(sRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sRecordsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE))
                    .addGroup(sRecordsLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(sRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sRecordsLayout.createSequentialGroup()
                                .addGroup(sRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbNameStd, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbYearlLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sRecordsLayout.createSequentialGroup()
                                .addGroup(sRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(sRecordsLayout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel6))
                                    .addComponent(lbContactStd, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbStationStd, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbAddressStd, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(32, 32, 32))
            .addGroup(sRecordsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sRecordsLayout.setVerticalGroup(
            sRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sRecordsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(sRecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sRecordsLayout.createSequentialGroup()
                        .addComponent(lblProfilePicture, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbNameStd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbYearlLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbContactStd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbStationStd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbAddressStd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(sRecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(81, 81, 81));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Work Immersion Timework Management ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1361, -1));

        jPanel4.setBackground(new java.awt.Color(112, 112, 112));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pic4.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton1.setText("Students");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addstudent.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        addstudent.setText("Add Student");
        addstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus3.png"))); // NOI18N

        barcode.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        barcode.setText("Barcode");
        barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/q4r.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addstudent)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(addstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(494, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 75, -1, -1));

        P1.setBackground(new java.awt.Color(232, 233, 215));
        P1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel2.setText("STUDENTS");

        jPanel9.setBackground(new java.awt.Color(117, 117, 117));
        jPanel9.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1073, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1073, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(P1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 88, -1, -1));

        studentInfoTab.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        studentInfoTab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                studentInfoTabStateChanged(evt);
            }
        });

        test1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                test1MouseClicked(evt);
            }
        });

        tbIctHope.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tbIctHope.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENTS ID", "NAME", "ADDRESS / STATION", "TOTAL RENDERED TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbIctHope.getTableHeader().setReorderingAllowed(false);
        test1.setViewportView(tbIctHope);
        if (tbIctHope.getColumnModel().getColumnCount() > 0) {
            tbIctHope.getColumnModel().getColumn(0).setResizable(false);
            tbIctHope.getColumnModel().getColumn(1).setResizable(false);
            tbIctHope.getColumnModel().getColumn(2).setResizable(false);
            tbIctHope.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pIctHopeLayout = new javax.swing.GroupLayout(pIctHope);
        pIctHope.setLayout(pIctHopeLayout);
        pIctHopeLayout.setHorizontalGroup(
            pIctHopeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(test1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE)
        );
        pIctHopeLayout.setVerticalGroup(
            pIctHopeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(test1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        studentInfoTab.addTab("ICT 12 HOPE", pIctHope);

        tbIctLove.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tbIctLove.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENTS ID", "NAME", "ADDRESS / STATION", "TOTAL RENDERED TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbIctLove.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbIctLove);
        if (tbIctLove.getColumnModel().getColumnCount() > 0) {
            tbIctLove.getColumnModel().getColumn(0).setResizable(false);
            tbIctLove.getColumnModel().getColumn(1).setResizable(false);
            tbIctLove.getColumnModel().getColumn(2).setResizable(false);
            tbIctLove.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pIctLoveLayout = new javax.swing.GroupLayout(pIctLove);
        pIctLove.setLayout(pIctLoveLayout);
        pIctLoveLayout.setHorizontalGroup(
            pIctLoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pIctLoveLayout.setVerticalGroup(
            pIctLoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        studentInfoTab.addTab("ICT 12 LOVE", pIctLove);

        tbHumssHope.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tbHumssHope.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENTS ID", "NAME", "ADDRESS / STATION", "TOTAL RENDERED TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbHumssHope.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tbHumssHope);
        if (tbHumssHope.getColumnModel().getColumnCount() > 0) {
            tbHumssHope.getColumnModel().getColumn(0).setResizable(false);
            tbHumssHope.getColumnModel().getColumn(1).setResizable(false);
            tbHumssHope.getColumnModel().getColumn(2).setResizable(false);
            tbHumssHope.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pHumsHopeLayout = new javax.swing.GroupLayout(pHumsHope);
        pHumsHope.setLayout(pHumsHopeLayout);
        pHumsHopeLayout.setHorizontalGroup(
            pHumsHopeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1859, Short.MAX_VALUE)
        );
        pHumsHopeLayout.setVerticalGroup(
            pHumsHopeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        studentInfoTab.addTab("HUMSS 12 HOPE", pHumsHope);

        tbHumssLove.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tbHumssLove.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENTS ID", "NAME", "ADDRESS / STATION", "TOTAL RENDERED TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbHumssLove.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tbHumssLove);
        if (tbHumssLove.getColumnModel().getColumnCount() > 0) {
            tbHumssLove.getColumnModel().getColumn(0).setResizable(false);
            tbHumssLove.getColumnModel().getColumn(1).setResizable(false);
            tbHumssLove.getColumnModel().getColumn(2).setResizable(false);
            tbHumssLove.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pHumssLoveLayout = new javax.swing.GroupLayout(pHumssLove);
        pHumssLove.setLayout(pHumssLoveLayout);
        pHumssLoveLayout.setHorizontalGroup(
            pHumssLoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1859, Short.MAX_VALUE)
        );
        pHumssLoveLayout.setVerticalGroup(
            pHumssLoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        studentInfoTab.addTab("HUMSS 12 LOVE", pHumssLove);

        tbHumssFaith.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tbHumssFaith.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENTS ID", "NAME", "ADDRESS / STATION", "TOTAL RENDERED TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbHumssFaith.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(tbHumssFaith);
        if (tbHumssFaith.getColumnModel().getColumnCount() > 0) {
            tbHumssFaith.getColumnModel().getColumn(0).setResizable(false);
            tbHumssFaith.getColumnModel().getColumn(1).setResizable(false);
            tbHumssFaith.getColumnModel().getColumn(2).setResizable(false);
            tbHumssFaith.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pHumssFaithLayout = new javax.swing.GroupLayout(pHumssFaith);
        pHumssFaith.setLayout(pHumssFaithLayout);
        pHumssFaithLayout.setHorizontalGroup(
            pHumssFaithLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1859, Short.MAX_VALUE)
        );
        pHumssFaithLayout.setVerticalGroup(
            pHumssFaithLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        studentInfoTab.addTab("HUMSS 12 FAITH", pHumssFaith);

        tbAbmLove.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tbAbmLove.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENTS ID", "NAME", "ADDRESS / STATION", "TOTAL RENDERED TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAbmLove.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(tbAbmLove);
        if (tbAbmLove.getColumnModel().getColumnCount() > 0) {
            tbAbmLove.getColumnModel().getColumn(0).setResizable(false);
            tbAbmLove.getColumnModel().getColumn(1).setResizable(false);
            tbAbmLove.getColumnModel().getColumn(2).setResizable(false);
            tbAbmLove.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pAbmLoveLayout = new javax.swing.GroupLayout(pAbmLove);
        pAbmLove.setLayout(pAbmLoveLayout);
        pAbmLoveLayout.setHorizontalGroup(
            pAbmLoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1859, Short.MAX_VALUE)
        );
        pAbmLoveLayout.setVerticalGroup(
            pAbmLoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        studentInfoTab.addTab("ABM 12 LOVE", pAbmLove);

        tbStemHope.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tbStemHope.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENTS ID", "NAME", "ADDRESS / STATION", "TOTAL RENDERED TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbStemHope.getTableHeader().setReorderingAllowed(false);
        jScrollPane8.setViewportView(tbStemHope);
        if (tbStemHope.getColumnModel().getColumnCount() > 0) {
            tbStemHope.getColumnModel().getColumn(0).setResizable(false);
            tbStemHope.getColumnModel().getColumn(1).setResizable(false);
            tbStemHope.getColumnModel().getColumn(2).setResizable(false);
            tbStemHope.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pStemHopeLayout = new javax.swing.GroupLayout(pStemHope);
        pStemHope.setLayout(pStemHopeLayout);
        pStemHopeLayout.setHorizontalGroup(
            pStemHopeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 1859, Short.MAX_VALUE)
        );
        pStemHopeLayout.setVerticalGroup(
            pStemHopeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        studentInfoTab.addTab("STEM 12 HOPE", pStemHope);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(studentInfoTab, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentInfoTab)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 203, 1160, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Tlobby record = new Tlobby();
        record.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentActionPerformed
        AddStudents records = new AddStudents();
        records.show();
        dispose();
    }//GEN-LAST:event_addstudentActionPerformed

    private void barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeActionPerformed
        Barcode records = new Barcode();
        records.show();
        dispose();
    }//GEN-LAST:event_barcodeActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        sRecords.setVisible(false);

    }//GEN-LAST:event_btnExitActionPerformed

    private void test1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test1MouseClicked

    }//GEN-LAST:event_test1MouseClicked

    private void studentInfoTabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_studentInfoTabStateChanged
        utils.refreshTable(studentInfoTab,
                repo,
                tbIctHope,
                tbIctLove,
                tbHumssHope,
                tbHumssLove,
                tbHumssFaith,
                tbAbmLove,
                tbStemHope);

        this.addListenersForAllTableInTabbed();


    }//GEN-LAST:event_studentInfoTabStateChanged

    private void jDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteStudentActionPerformed
        int option = JOptionPane.showConfirmDialog(this, "Do you want to delete this?");
        int selectedTab = studentInfoTab.getSelectedIndex();
        int selectedRow = mapTable.get(selectedTab).getSelectedRow();
        String studentId = (String) mapTable.get(selectedTab).getValueAt(selectedRow, 0);

        repo.deleteStudents(studentId);

        utils.refreshTable(studentInfoTab,
                repo,
                tbIctHope,
                tbIctLove,
                tbHumssHope,
                tbHumssLove,
                tbHumssFaith,
                tbAbmLove,
                tbStemHope);


    }//GEN-LAST:event_jDeleteStudentActionPerformed

    private void jStudentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStudentInfoActionPerformed

        int selectedTab = studentInfoTab.getSelectedIndex();

        int selectedRow = mapTable.get(selectedTab).getSelectedRow();

        String studentId = (String) mapTable.get(selectedTab).getValueAt(selectedRow, 0);

        ResultSet rs = repo.studentInformation(studentId);
        sRecords.setVisible(true);
        sRecords.repaint();
        sRecords.revalidate();

        try {
            if (rs.next()) {
                String stdyearInfo = rs.getString("s.strand") + " "
                        + rs.getString("s.year_level") + " " + rs.getString("s.section");

                lbNameStd.setText(rs.getString("s.student_name"));
                lbStudentId.setText(rs.getString("s.student_id"));
                lbAddressStd.setText(rs.getString("a.address"));
                lbContactStd.setText(rs.getString("a.contact_no"));
                lbYearlLevel.setText(stdyearInfo);
                lbStationStd.setText(rs.getString("a.station"));

                Blob blob = rs.getBlob("p.profile_picture");
                try {
                    utils.setImageInLabel(lblProfilePicture, blob);
                } catch (IOException ex) {
                    Logger.getLogger(Tlobby.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            addTimeInOutInStudentsInfo(studentId);
        } catch (SQLException ex) {
            Logger.getLogger(Tlobby.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jStudentInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tlobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tlobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tlobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tlobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tlobby().setVisible(true);
            }
        });
    }

    private void checkForPopup(MouseEvent e, JTable table) {
        if (e.isPopupTrigger()) {
            int row = table.rowAtPoint(e.getPoint());
            if (row >= 0) {
                table.setRowSelectionInterval(row, row);
            }
            jPopMenu.show(e.getComponent(), e.getX(), e.getY());
        }
    }

    public void addListenersForAllTableInTabbed() {
        int selectIndex = studentInfoTab.getSelectedIndex();

        JTable selectedTable = mapTable.get(selectIndex);

        if (selectedTable != null) {
            // Remove existing listeners to prevent duplicates
            for (MouseListener ml : selectedTable.getMouseListeners()) {
                selectedTable.removeMouseListener(ml);
            }
            selectedTable.addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e) {
                    checkForPopup(e, selectedTable);
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                    checkForPopup(e, selectedTable);
                }
            });
        }
    }

    private void addTimeInOutInStudentsInfo(String userId) {
        try (ResultSet rs = repo.getStudentTracker(userId)) {
            DefaultTableModel dft = (DefaultTableModel) tblTimeInOut.getModel();

            dft.setRowCount(0);
            SimpleDateFormat dateForrmatter = new SimpleDateFormat("EE, MMM dd, yyyy");
            DateTimeFormatter timeForrmatter = DateTimeFormatter.ofPattern("hh:mm:ss a");

            while (rs.next()) {
               
                Date dateIn = rs.getDate("date_in");
                String dateFormatted = dateForrmatter.format(dateIn);
                LocalTime timeIn = rs.getTime("time_in").toLocalTime();
                LocalTime timeout = rs.getTime("time_out").toLocalTime();
                
                String timeInFormatted = timeForrmatter.format(timeIn);// format time
                String timeOutFormatted = timeForrmatter.format(timeout);
               
                dft.addRow(new Object[]{
                    dateFormatted, timeInFormatted, timeOutFormatted
                }
                );

            }
        } catch (Exception e) {
        }
    }

    // Apply listener to all tables in the tabbed pane

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P1;
    private javax.swing.JButton addstudent;
    private javax.swing.JButton barcode;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jDeleteStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopMenu;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JMenuItem jStudentInfo;
    private javax.swing.JLabel lbAddressStd;
    private javax.swing.JLabel lbContactStd;
    private javax.swing.JLabel lbNameStd;
    private javax.swing.JLabel lbStationStd;
    private javax.swing.JLabel lbStudentId;
    private javax.swing.JLabel lbYearlLevel;
    private javax.swing.JLabel lblProfilePicture;
    private javax.swing.JPanel pAbmLove;
    private javax.swing.JPanel pHumsHope;
    private javax.swing.JPanel pHumssFaith;
    private javax.swing.JPanel pHumssLove;
    private javax.swing.JPanel pIctHope;
    private javax.swing.JPanel pIctLove;
    private javax.swing.JPanel pStemHope;
    private javax.swing.JPanel sRecords;
    private javax.swing.JTabbedPane studentInfoTab;
    private javax.swing.JTable tbAbmLove;
    private javax.swing.JTable tbHumssFaith;
    private javax.swing.JTable tbHumssHope;
    private javax.swing.JTable tbHumssLove;
    private javax.swing.JTable tbIctHope;
    private javax.swing.JTable tbIctLove;
    private javax.swing.JTable tbStemHope;
    private javax.swing.JTable tblTimeInOut;
    private javax.swing.JScrollPane test1;
    // End of variables declaration//GEN-END:variables
}
