
import java.sql.ResultSet;
import database.StudentsRepository;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import utils.Utility;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vhalv
 */
public class Tlobby extends javax.swing.JFrame {
private Utility utils = new Utility();
private StudentsRepository repo = new StudentsRepository();
    public Tlobby() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Srecords = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sv2 = new javax.swing.JButton();
        jPopMenu = new javax.swing.JPopupMenu();
        deleteStudent = new javax.swing.JMenuItem();
        studentInfo = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        addstudent = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        barcode = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        P1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        studentInfoTab = new javax.swing.JTabbedPane();
        pIctHope = new javax.swing.JPanel();
        test1 = new javax.swing.JScrollPane();
        tbIctHope = new javax.swing.JTable();
        pIctLove = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbIctLove = new javax.swing.JTable();
        pHumsHope = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbHumssHope = new javax.swing.JTable();
        pHumssLove = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbHumssLove = new javax.swing.JTable();
        pHumssFaith = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbHumssFaith = new javax.swing.JTable();
        pAbmLove = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbAbmLove = new javax.swing.JTable();
        pStemHope = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbStemHope = new javax.swing.JTable();

        Srecords.setBackground(new java.awt.Color(232, 233, 215));

        jLabel6.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel6.setText("STUDENT RECORDS");

        jPanel14.setBackground(new java.awt.Color(117, 117, 117));
        jPanel14.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DATE", "TIME IN", "TIME OUT"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel9.setText("Name:");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel8.setText("Student ID:");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel10.setText("Grade / Section:");

        sv2.setBackground(new java.awt.Color(0, 102, 51));
        sv2.setForeground(new java.awt.Color(255, 255, 255));
        sv2.setText("EXIT");
        sv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sv2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SrecordsLayout = new javax.swing.GroupLayout(Srecords);
        Srecords.setLayout(SrecordsLayout);
        SrecordsLayout.setHorizontalGroup(
            SrecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SrecordsLayout.createSequentialGroup()
                .addGroup(SrecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SrecordsLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6))
                    .addGroup(SrecordsLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(sv2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SrecordsLayout.createSequentialGroup()
                .addGroup(SrecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SrecordsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, 1238, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SrecordsLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(SrecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        SrecordsLayout.setVerticalGroup(
            SrecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SrecordsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(SrecordsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(SrecordsLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sv2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        deleteStudent.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        deleteStudent.setText("DELETE");
        deleteStudent.setToolTipText("");
        jPopMenu.add(deleteStudent);
        deleteStudent.getAccessibleContext().setAccessibleName("Menu2");

        studentInfo.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        studentInfo.setText("ACCOUNT");
        jPopMenu.add(studentInfo);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(81, 81, 81));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Work Immersion Timework Management ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );

        jPanel4.setBackground(new java.awt.Color(112, 112, 112));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pic4.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton1.setText("Students");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addstudent.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        addstudent.setText("Add Student");
        addstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus3.png"))); // NOI18N

        barcode.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        barcode.setText("Barcode");
        barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/q4r.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barcode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addstudent)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(addstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(485, Short.MAX_VALUE))
        );

        P1.setBackground(new java.awt.Color(232, 233, 215));
        P1.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel2.setText("STUDENTS");

        jPanel9.setBackground(new java.awt.Color(117, 117, 117));
        jPanel9.setPreferredSize(new java.awt.Dimension(0, 3));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1073, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1073, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(P1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        studentInfoTab.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        studentInfoTab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                studentInfoTabStateChanged(evt);
            }
        });

        test1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                test1MouseClicked(evt);
            }
        });

        tbIctHope.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tbIctHope.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENTS ID", "NAME", "ADDRESS / STATION", "TOTAL RENDERED TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbIctHope.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbIctHopeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbIctHopeMouseReleased(evt);
            }
        });
        test1.setViewportView(tbIctHope);
        if (tbIctHope.getColumnModel().getColumnCount() > 0) {
            tbIctHope.getColumnModel().getColumn(0).setResizable(false);
            tbIctHope.getColumnModel().getColumn(1).setResizable(false);
            tbIctHope.getColumnModel().getColumn(2).setResizable(false);
            tbIctHope.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pIctHopeLayout = new javax.swing.GroupLayout(pIctHope);
        pIctHope.setLayout(pIctHopeLayout);
        pIctHopeLayout.setHorizontalGroup(
            pIctHopeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(test1, javax.swing.GroupLayout.DEFAULT_SIZE, 1859, Short.MAX_VALUE)
        );
        pIctHopeLayout.setVerticalGroup(
            pIctHopeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(test1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        studentInfoTab.addTab("ICT 12 HOPE", pIctHope);

        tbIctLove.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tbIctLove.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENTS ID", "NAME", "ADDRESS / STATION", "TOTAL RENDERED TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbIctLove);
        if (tbIctLove.getColumnModel().getColumnCount() > 0) {
            tbIctLove.getColumnModel().getColumn(0).setResizable(false);
            tbIctLove.getColumnModel().getColumn(1).setResizable(false);
            tbIctLove.getColumnModel().getColumn(2).setResizable(false);
            tbIctLove.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pIctLoveLayout = new javax.swing.GroupLayout(pIctLove);
        pIctLove.setLayout(pIctLoveLayout);
        pIctLoveLayout.setHorizontalGroup(
            pIctLoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pIctLoveLayout.setVerticalGroup(
            pIctLoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        studentInfoTab.addTab("ICT 12 LOVE", pIctLove);

        tbHumssHope.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tbHumssHope.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENTS ID", "NAME", "ADDRESS / STATION", "TOTAL RENDERED TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbHumssHope);
        if (tbHumssHope.getColumnModel().getColumnCount() > 0) {
            tbHumssHope.getColumnModel().getColumn(0).setResizable(false);
            tbHumssHope.getColumnModel().getColumn(1).setResizable(false);
            tbHumssHope.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout pHumsHopeLayout = new javax.swing.GroupLayout(pHumsHope);
        pHumsHope.setLayout(pHumsHopeLayout);
        pHumsHopeLayout.setHorizontalGroup(
            pHumsHopeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1859, Short.MAX_VALUE)
        );
        pHumsHopeLayout.setVerticalGroup(
            pHumsHopeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        studentInfoTab.addTab("HUMSS 12 HOPE", pHumsHope);

        tbHumssLove.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tbHumssLove.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENTS ID", "NAME", "ADDRESS / STATION", "TOTAL RENDERED TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tbHumssLove);
        if (tbHumssLove.getColumnModel().getColumnCount() > 0) {
            tbHumssLove.getColumnModel().getColumn(0).setResizable(false);
            tbHumssLove.getColumnModel().getColumn(1).setResizable(false);
            tbHumssLove.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout pHumssLoveLayout = new javax.swing.GroupLayout(pHumssLove);
        pHumssLove.setLayout(pHumssLoveLayout);
        pHumssLoveLayout.setHorizontalGroup(
            pHumssLoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1859, Short.MAX_VALUE)
        );
        pHumssLoveLayout.setVerticalGroup(
            pHumssLoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        studentInfoTab.addTab("HUMSS 12 LOVE", pHumssLove);

        tbHumssFaith.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tbHumssFaith.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENTS ID", "NAME", "ADDRESS / STATION", "TOTAL RENDERED TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tbHumssFaith);
        if (tbHumssFaith.getColumnModel().getColumnCount() > 0) {
            tbHumssFaith.getColumnModel().getColumn(0).setResizable(false);
            tbHumssFaith.getColumnModel().getColumn(1).setResizable(false);
            tbHumssFaith.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout pHumssFaithLayout = new javax.swing.GroupLayout(pHumssFaith);
        pHumssFaith.setLayout(pHumssFaithLayout);
        pHumssFaithLayout.setHorizontalGroup(
            pHumssFaithLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1859, Short.MAX_VALUE)
        );
        pHumssFaithLayout.setVerticalGroup(
            pHumssFaithLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        studentInfoTab.addTab("HUMSS 12 FAITH", pHumssFaith);

        tbAbmLove.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tbAbmLove.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENTS ID", "NAME", "ADDRESS / STATION", "TOTAL RENDERED TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tbAbmLove);
        if (tbAbmLove.getColumnModel().getColumnCount() > 0) {
            tbAbmLove.getColumnModel().getColumn(0).setResizable(false);
            tbAbmLove.getColumnModel().getColumn(1).setResizable(false);
            tbAbmLove.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout pAbmLoveLayout = new javax.swing.GroupLayout(pAbmLove);
        pAbmLove.setLayout(pAbmLoveLayout);
        pAbmLoveLayout.setHorizontalGroup(
            pAbmLoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1859, Short.MAX_VALUE)
        );
        pAbmLoveLayout.setVerticalGroup(
            pAbmLoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        studentInfoTab.addTab("ABM 12 LOVE", pAbmLove);

        tbStemHope.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        tbStemHope.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STUDENTS ID", "NAME", "ADDRESS / STATION", "TOTAL RENDERED TIME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tbStemHope);
        if (tbStemHope.getColumnModel().getColumnCount() > 0) {
            tbStemHope.getColumnModel().getColumn(0).setResizable(false);
            tbStemHope.getColumnModel().getColumn(1).setResizable(false);
            tbStemHope.getColumnModel().getColumn(2).setResizable(false);
            tbStemHope.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pStemHopeLayout = new javax.swing.GroupLayout(pStemHope);
        pStemHope.setLayout(pStemHopeLayout);
        pStemHopeLayout.setHorizontalGroup(
            pStemHopeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 1859, Short.MAX_VALUE)
        );
        pStemHopeLayout.setVerticalGroup(
            pStemHopeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        studentInfoTab.addTab("STEM 12 HOPE", pStemHope);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(studentInfoTab, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentInfoTab)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Tlobby record = new Tlobby();
        record.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentActionPerformed
        AddStudents records = new AddStudents();
        records.show();
        dispose();
    }//GEN-LAST:event_addstudentActionPerformed

    private void barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeActionPerformed
        Barcode records = new Barcode();
        records.show();
        dispose();
    }//GEN-LAST:event_barcodeActionPerformed

    private void sv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sv2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sv2ActionPerformed

    private void test1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_test1MouseClicked

    }//GEN-LAST:event_test1MouseClicked

    private void studentInfoTabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_studentInfoTabStateChanged
        int selectedIndex = studentInfoTab.getSelectedIndex();
        String title = studentInfoTab.getTitleAt(selectedIndex);
        
        String slicedTitleTab [] = title.split(" ");
        
        String strand = slicedTitleTab[0];
        int yearLevel = Integer.parseInt(slicedTitleTab[1]);
        String section = slicedTitleTab[2];
        
        int count = repo.countValues(strand, section, yearLevel);
        
        
            Map<Integer, JTable> tableMap = new HashMap<>();
            tableMap.put(0, tbIctHope);
            tableMap.put(1, tbIctLove);
            tableMap.put(2, tbHumssHope);
            tableMap.put(3, tbHumssLove);
            tableMap.put(4, tbHumssFaith);
            tableMap.put(5, tbAbmLove);
            tableMap.put(6, tbStemHope);
        try {
            ResultSet rs = repo.getStudentsRecords(strand, yearLevel, section);
            DefaultTableModel dft = (DefaultTableModel)  tableMap.get(selectedIndex).getModel();
            dft.setRowCount(0);
            while (rs.next()) {                
                 utils.setValueInTable(
                         tableMap.get(selectedIndex), 
                         rs.getString("student_id"), 
                         rs.getString("student_name"), 
                         rs.getString("address"),
                         rs.getString("station"), 
                         section, 
                         count);
            }


        } catch (Exception e) {
        } finally {
        }

        
        
        
        
    }//GEN-LAST:event_studentInfoTabStateChanged

    private void tbIctHopeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbIctHopeMouseReleased
    
        
    }//GEN-LAST:event_tbIctHopeMouseReleased

    private void tbIctHopeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbIctHopeMousePressed
           if (evt.isPopupTrigger()) {
        int row = tbIctHope.rowAtPoint(evt.getPoint());
        if (row >= 0) {
            tbIctHope.setRowSelectionInterval(row, row);
        }
        jPopMenu.show(evt.getComponent(), evt.getX(), evt.getY()); 
           }
        int selectedRow = tbIctHope.getSelectedRow();
        
        System.out.println(tbIctHope.getValueAt(selectedRow, 0));
        
    }//GEN-LAST:event_tbIctHopeMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tlobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tlobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tlobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tlobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tlobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P1;
    private javax.swing.JPanel Srecords;
    private javax.swing.JButton addstudent;
    private javax.swing.JButton barcode;
    private javax.swing.JMenuItem deleteStudent;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pAbmLove;
    private javax.swing.JPanel pHumsHope;
    private javax.swing.JPanel pHumssFaith;
    private javax.swing.JPanel pHumssLove;
    private javax.swing.JPanel pIctHope;
    private javax.swing.JPanel pIctLove;
    private javax.swing.JPanel pStemHope;
    private javax.swing.JMenuItem studentInfo;
    private javax.swing.JTabbedPane studentInfoTab;
    private javax.swing.JButton sv2;
    private javax.swing.JTable tbAbmLove;
    private javax.swing.JTable tbHumssFaith;
    private javax.swing.JTable tbHumssHope;
    private javax.swing.JTable tbHumssLove;
    private javax.swing.JTable tbIctHope;
    private javax.swing.JTable tbIctLove;
    private javax.swing.JTable tbStemHope;
    private javax.swing.JScrollPane test1;
    // End of variables declaration//GEN-END:variables
}
